apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox-echo
  name: busybox-echo
  namespace: sodikmirzo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-echo
  template:
    metadata:
      labels:
        app: busybox-echo
    spec:
      containers:
        - image: busybox
          name: busybox
          command: ['sh', '-c', 'echo "The best DevOps Course!"']
