apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    last: final
    author: sodikmirzo
  name: nginx1
  namespace: sodikmirzo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
