apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-exam
  namespace: sodikmirzo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: final-exam
  template:
    metadata:
      labels:
        app: final-exam
    spec:
      containers:
        - name: flask-app
          image: nvrbckdown/flask-app:final-exam
          ports:
            - containerPort: 5000
          env:
            - name: AUTHOR
              value: "Sodikmirzo"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
